export const environment = {
  production: true,
  // apiUrl: 'https://localhost:44352/api/v1'
   //local
  //  apiUrl: 'http://51.91.200.130:804/api/v1',
  //  oldUrl: 'http://localhost:2634/'
  //QA
//  apiUrl: 'http://103.251.94.95:804/api/v1',
//   oldUrl: 'http://103.251.94.95:802',
 apiUrl: 'https://api.shreeharienterprise.co.in',
  oldUrl: 'https://api.shreeharienterprise.co.in/home',
//live
  // apiUrl: 'http://103.251.94.95:806/api/v1',
  // oldUrl: 'http://103.251.94.95:801'
  ManufactureWorkTypeId : 2,
  supervisorrole: '9',
  ResourceMasterIds: {
    Dashbord: 1,
    JobWorkOrderReport: 2,
    ManufactureOrderReport: 3,
    DailyWorkStatus: 4,
    ClientMaster: 5,
    VendorMaster: 6,
    CustomerMaster: 7,
    WorkerReport: 8,
    AssignTask: 9,
    // WorkerReportt: 10,
    StockReport: 11,
    TransactionMaster: 12,
    RoleMaster: 13,
    MasterPage:14,
    ProductionReport:15,
    SellingReport:16,
    GetMoneyFrom:17,
    GiveMoneyTo:18,

    EmployeeWorkerReport : 19,
      // LocationReportsViewManpowerLocationDetails: 14,
      // ReportsHelpdeskSR1: 15,
      // ReportsAttendanceReport: 16,
      // ReportsDPRNGConversion: 17,
      // ReportsDPRRFCTracker: 18,
      // ReportsPETrackerReport: 19,
      // ReportsCallCenterReport: 20,
      // ReportsTicketClosureReport: 21,
      // ReportsManpowerPerformanceReport: 22,
      // ReportsBillingReport: 23,
      // ReportsIncompleteSRStatusReport: 24,
      // ReportsTATReport: 25,
      // ReportsProjectReport: 26,
      // ReportsMaterialReceiptReport: 27,
      // ReportsMaterialIssue: 28,
      // ReportsMaterialReturn: 29,
      // ReportsConsumptionReport: 30,
      // ReportsStockReport: 31,
      // ReportsContractorReconciliationReport: 32,
      // ReportsdailyProgressReport: 33,
      // ReportsMaterialRequisitionReport: 34,
      // ReportsMaterialTrasnferReport: 35,
      // Company: 36,
      // ManageClient: 37,
      // ServiceMaster: 38,
      // ServiceCategory: 39,
      // ServiceSubCategory: 40,
      // MaterialCategoryMaster: 41,
      // ControlRoomMaster: 42,
      // SiteMaster: 43,
      // ContractMaster: 44,
      // ZoneMaster: 45,
      // ManageUser: 46,
      // ManpowerMaster: 47,
      // // RoleMaster: 13,
      // MaterialRequisitionPlaningMaterialRequisition: 61,
      // PurchaseOrder: 62,
      // ContractService_ContractorMaste_WorkOrder: 63,
      // ContractService_WotkOrder: 64,
  },
};
